# Generated by Django 5.2.17 on 2026-08-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('avatar', models.URLField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('rank_icon', models.CharField(blank=True, max_length=10)),
                ('total_repos', models.IntegerField(default=0)),
                ('total_stars', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
